name: Python Tests

on: [push, pull_request]  # Триггеры

jobs:
  test:
    runs-on: ubuntu-latest  # Используем GitHub-hosted runner
    
    steps:
    - uses: actions/checkout@v4  # Клонирует репозиторий
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'  # Аналог image: python:3.11-slim
        
    - name: Install dependencies
      run: |
        pip install -r requirements.txt
        pip install mypy black isort flake8 pytest  # Устанавливаем инструменты
        
    - name: Run mypy
      run: mypy app/
      
    - name: Run black
      run: black --check --diff app/
      
    - name: Run isort
      run: isort --check-only --diff app/
      
    - name: Run flake8
      run: flake8 app/
